ProjectA.DKHBSolution/ProjectA/Controllers/XetHocBongController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectA.Models;
using ProjectA.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectA.Controllers
{
    public class XetHocBongController : Controller
    {
        private readonly IXetHocBong _XetHocBong;
        private readonly ApplicationDbContext _context;
        public XetHocBongController(IXetHocBong XetHocBong, ApplicationDbContext context)
        {
            _XetHocBong = XetHocBong;
            _context = context;
        }

        public IActionResult Index(int? page = 0)
        {
            int limit = 7;
            int start;
            if (page > 0)
            {
                page = page + 0;
            }
            else
            {
                page = 1;
            }
            start = (int)(page - 1) * limit;

            ViewBag.pageCurrent = page;

            int totalProduct = _XetHocBong.totalProduct();

            ViewBag.totalProduct = totalProduct;

            ViewBag.numberPage = _XetHocBong.numberPage(totalProduct, limit);

            var data = _XetHocBong.paginationProduct(start, limit);

            return View(data.ToList());
        }

       
    }
}

ProjectA.DKHBSolution/ProjectA/Views/XetHocBong/Index.cshtml
@model IEnumerable<ProjectA.ViewModel.XetHocBongViewModel>
@{Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Active"] = "XHB";}

<h2>Danh sách đạt được học bổng</h2>
<table class="table table-striped table-bordered table-white">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.IdSinhVien)</th>
            <th>@Html.DisplayNameFor(model => model.TenSinhVien)</th>
            <th>@Html.DisplayNameFor(model => model.IdLop)</th>
            <th>@Html.DisplayNameFor(model => model.IdHocKy)</th>
            <th>@Html.DisplayNameFor(model => model.DiemThang4)</th>
            <th>@Html.DisplayNameFor(model => model.DiemThang10)</th>
            <th>@Html.DisplayNameFor(model => model.SoTinChi)</th>
            <th>@Html.DisplayNameFor(model => model.XepLoai)</th>
            <th>@Html.DisplayNameFor(model => model.SoTien)</th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.IdSinhVien</td>
                <td>@item.TenSinhVien</td>
                <td>@item.IdLop</td>
                <td>@item.IdHocKy</td>
                <td>@item.DiemThang4</td>
                <td>@item.DiemThang10</td>
                <td>@item.SoTinChi</td>
                <td>@item.XepLoai</td>
                <td>@item.SoTien</td>
                @*<th>
                        <a asp-action="Edit" asp-route-id="@item.IdSinhVien">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.IdSinhVien">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.IdSinhVien">Delete</a>
                    </th>*@
            </tr>
        }
    </tbody>
</table>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        @{
            int numberPage = ViewBag.numberPage;
            int pageCurrent = ViewBag.pageCurrent;
            int offset = 2;//number display page
            if (pageCurrent > 1)
            {
                int prevPage = pageCurrent - 1;
                var PrevLink = new Dictionary<string, string> { { "page", prevPage.ToString() } };
                @*<li><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="PrevLink">Prev Link</a></li>*@
                <li class="page-item">
                    <a class="page-link" aria-label="Previous" asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="PrevLink">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }
            int from = pageCurrent - offset;
            int to = pageCurrent + offset;
            if (from <= 0)
            {
                from = 1;
                to = offset * 2;
            }


            if (to > numberPage)
            {
                to = numberPage;
            }

            int i;
            for (i = from; i <= to; i++)
            {
                var parms = new Dictionary<string, string>
                {
                        { "page",i.ToString()}
                    };
                if (pageCurrent == i)
                {
                    <li class="page-item active"><a class="page-link" asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="parms">@i</a></li>
                    @*<li class="active"><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="parms">@i</a></li>*@
                }
                else
                {
                    <li class="page-item"><a class="page-link" asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="parms">@i</a></li>
                    @*<li><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="parms">@i</a></li>*@
                }

            }

            if (pageCurrent < numberPage)
            {
                int nextPage = pageCurrent + 1;
                var NextLink = new Dictionary<string, string> { { "page", nextPage.ToString() } };
                @*<li><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="NextLink">Next Link</a></li>*@
                <li class="page-item">
                    <a class="page-link" asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="NextLink" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }

            if (pageCurrent < numberPage - (to / 2))
            {
                var LastLink = new Dictionary<string, string> { { "page", numberPage.ToString() } };
                <li class="page-item">
                    <a class="page-link" asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="LastLink">
                        <span aria-hidden="true">&#8921;</span>
                    </a>
                </li>
                @*<li><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="LastLink">Last Link</a></li>*@
            }

        }

    </ul>
</nav>
@*<ul class="pagination">
    @{
        int numberPage = ViewBag.numberPage;
        int pageCurrent = ViewBag.pageCurrent;
        int offset = 2;//number display page


        //config FirstLink
        if (pageCurrent > 1)
        {
            int prevPage = pageCurrent - 1;
            var PrevLink = new Dictionary<string, string> { { "page", prevPage.ToString() } };
            <li><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="PrevLink">Prev Link</a></li>
        }

        int from = pageCurrent - offset;
        int to = pageCurrent + offset;
        if (from <= 0)
        {
            from = 1;
            to = offset * 2;
        }


        if (to > numberPage)
        {
            to = numberPage;
        }

        int i;
        for (i = from; i <= to; i++)
        {
            var parms = new Dictionary<string, string>
                {
                        { "page",i.ToString()}
                    };
            if (pageCurrent == i)
            {
                <li class="active"><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="parms">@i</a></li>
            }
            else
            {
                <li><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="parms">@i</a></li>
            }

        }

        if (pageCurrent < numberPage - (to / 2))
        {
            <li><a>...</a></li>
            var LastLink = new Dictionary<string, string> { { "page", numberPage.ToString() } };
            <li><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="LastLink">Last Link</a></li>
        }

        if (pageCurrent < numberPage)
        {
            int nextPage = pageCurrent + 1;
            var NextLink = new Dictionary<string, string> { { "page", nextPage.ToString() } };
            <li><a asp-controller="XetHocBong" asp-action="Index" asp-all-route-data="NextLink">Next Link</a></li>
        }
    }
</ul>*@

ProjectA.DKHBSolution/ProjectA/Views/XetHocBong/__Paging.cshtml
@model dynamic
@{
    int currentPage = Model.currentPage;
    int countPages = Model.countPages;
    var generateUrl = Model.generateUrl;

    if (currentPage > countPages)
        currentPage = countPages;

    if (countPages <= 1) return;


    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();


    int delta = 5;             // Số trang mở rộng về mỗi bên trang hiện tại
    int remain = delta * 2;      // Số trang hai bên trang hiện tại
    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i <= countPages)
        {
            pagesRanges.Add(currentPage + i);
            remain--;
        }

        if (currentPage - i >= 1)
        {
            pagesRanges.Insert(0, currentPage - i);
            remain--;
        }

    }
    // Xử lý thêm vào các trang cho đủ remain (xảy ra ở đầu mút của khoảng trang không đủ
    // trang chèn  vào)
    if (remain > 0)
    {
        if (pagesRanges[0] == 1)
        {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages)
                {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else
        {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1)
                {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}


<ul class="pagination">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Trang trước</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }

    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage)
        {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        }
        else
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Trang sau</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>