ProjectA.DKHBSolution/ProjectA/Models/SinhVien.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace ProjectA.Models
{
    public partial class SinhVien
    {
        public SinhVien()
        {
            DangKyHocBongs = new HashSet<DangKyHocBong>();
        }
        [Required(ErrorMessage = "Mã sinh viên phải bắt buộc")]
        [DisplayName("Mã sinh viên")]
        public string IdSinhVien { get; set; }

        [Required(ErrorMessage = "Lớp phải bắt buộc")]
        [DisplayName("Lớp")]
        public string IdLop { get; set; }

        [Required(ErrorMessage = "Tên sinh viên phải bắt buộc")]
        [DisplayName("Tên sinh viên")]
        public string TenSinhVien { get; set; }

        [Required(ErrorMessage = "Mật khẩu phải bắt buộc")]
        [DisplayName("Mật khẩu")]
        public string PasswordSv { get; set; }

        [Required(ErrorMessage = "Ngày sinh phải bắt buộc")]
        [DisplayName("Ngày sinh")]
        public DateTime? NgaySinh { get; set; }

        
        [DisplayName("Email")]
        public string Email { get; set; }

        
        [DisplayName("Số điện thoại")]
        public string SoDienThoai { get; set; }

        [Required(ErrorMessage = "Giới tính phải bắt buộc")]
        [DisplayName("Giới tính")]
        public string GioiTinh { get; set; }

        
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }

        public virtual ICollection<Diem> Diems { get; set; }
        public virtual Lop IdLopNavigation { get; set; }
        public virtual ICollection<DangKyHocBong> DangKyHocBongs { get; set; }
    }
}

ProjectA.DKHBSolution/ProjectA/Controllers/SinhVienController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using ProjectA.Models;
using ProjectA.Service;
using ProjectA.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectA.Controllers
{
    [Authorize]
    public class SinhVienController : Controller
    {
        private readonly ISinhVien _SinhVien;
        private readonly ILop _Lop;
        private readonly IHocKy _HocKy;
        private readonly ApplicationDbContext _context;
       
        public SinhVienController(ISinhVien SinhVien, ILop Lop, IHocKy HocKy, ApplicationDbContext context)
        {
            _SinhVien = SinhVien;
            _Lop = Lop;
            _HocKy = HocKy;
            _context = context;
        }

        public IActionResult Index(int? page = 0)
        {
            int limit = 7;
            int start;
            if (page > 0)
            {
               page = page + 0;
            }
            else
            {
                page = 1;
            }
            start = (int)(page - 1) * limit;

            ViewBag.pageCurrent = page;

            int totalProduct = _SinhVien.totalProduct();

            ViewBag.totalProduct = totalProduct;

            ViewBag.numberPage = _SinhVien.numberPage(totalProduct, limit);

            var data = _SinhVien.paginationProduct(start, limit);

            return View(data.ToList());
        }

        //public async Task<List<XetHocBongViewModel>> Index(IFormFile file)
        //{
        //    var sinhVien = from sv in _context.SinhViens
        //                   join d in _context.Diems on sv.IdSinhVien equals d.IdSinhVien                          
        //                   join hk in _context.HocKies on d.IdHocKy equals hk.IdHocKy
        //                   select new { sv, d, hk };
        //    var list = new List<XetHocBongViewModel>();
        //    using (var stream = new MemoryStream())
        //    {
        //        await file.CopyToAsync(stream);
        //        using (var package = new ExcelPackage(stream))
        //        {
        //            ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
        //            var rowcount = worksheet.Dimension.Rows;
        //            for (int row = 2; row <= rowcount; row++)
        //            {
        //                list.Add(new XetHocBongViewModel
        //                {
        //                    IdSinhVien = worksheet.Cells[row, 1].Value.ToString().Trim(),
        //                    TenSinhVien = worksheet.Cells[row, 2].Value.ToString().Trim(),
        //                    DiemThang10 = Convert.ToDouble(worksheet.Cells[row, 3].Value),
        //                    DiemThang4 = Convert.ToDouble(worksheet.Cells[row, 4].Value),
        //                    IdHocKy = worksheet.Cells[row, 5].Value.ToString().Trim(),
        //                    DiemRenLuyen = Convert.ToByte(worksheet.Cells[row, 6].Value),
        //                    XepLoai = worksheet.Cells[row, 7].Value.ToString().Trim(),
        //                    SoTinChi = Convert.ToInt32(worksheet.Cells[row, 8].Value),
        //                });
        //            }
        //        }
                
        //        return list;
        //    }
        //}


        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.SinhViens = _SinhVien.GetStudents;
            ViewBag.HocKies = _HocKy.GetHocKies;
            ViewBag.Lops = _Lop.GetAllLops;
            return View(_SinhVien.Create());
        }

        [HttpPost]
        public IActionResult Create(Diem sinhVien)
        {
            if (ModelState.IsValid)
            {
                _SinhVien.Add(sinhVien);

                return RedirectToAction("Index");
            }
            return View("Index");
        }

        [HttpGet]
        public IActionResult CreateNewSinhVien()
        {          
            ViewBag.Lops = _Lop.GetAllLops;
            return View(_SinhVien.CreateNewSinhVien());
        }

        [HttpPost]
        public IActionResult CreateNewSinhVien(SinhVien sinhVien)
        {
            if (ModelState.IsValid)
            {
                _SinhVien.AddNewSinhVien(sinhVien);

                return RedirectToAction("Create");
            }
            return View("Create");
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            var b = _SinhVien.Get(id);
            if (b == null)
                return NotFound();
            else
                return View(b);
        }

        [HttpPost]
        public IActionResult Delete(SinhVien sinhVien)
        {
            _SinhVien.Remove(sinhVien.IdSinhVien);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            ViewBag.Lops = _Lop.GetAllLops;
            return base.View(_SinhVien.Get(id));
        }

        [HttpPost]
        public IActionResult Edit(SinhVien sinhVien)
        {
            if (ModelState.IsValid)
            {
                //ViewBag.Lops = _Lop.GetAllLops;
                _SinhVien.Update(sinhVien);
                return RedirectToAction("Index");
            }
            return View("Index");
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            var sinhVien = _SinhVien.GetSinhVienById(id);
            if (sinhVien == null)
                return NotFound();
            else
                return View(sinhVien);
        }       
    }
}

ProjectA.DKHBSolution/ProjectA/Views/SinhVien/Create.cshtml
@model ProjectA.Models.Diem

@{
    ViewData["Title"] = "Create";
}

<h2>Thêm sinh viên</h2>

<a class="btn btn-outline-info" asp-action="CreateNewSinhVien" asp-controller="SinhVien"><i class="fas fa-plus"></i> Tạo sinh viên mới</a>
<hr />
<form asp-action="Create">
    <div class="row">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdSinhVien" class="control-label"></label>
                <select asp-for="IdSinhVien" class="form-control"
                        asp-items="@(new SelectList(ViewBag.SinhViens,"IdSinhVien","IdSinhVien"))">
                </select>
                <span asp-validation-for="IdSinhVien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdHocKy" class="control-label"></label>
                <select asp-for="IdHocKy" class="form-control"
                        asp-items="@(new SelectList(ViewBag.HocKies,"IdHocKy","IdHocKy"))">
                </select>
                <span asp-validation-for="IdHocKy" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DiemThang10" class="control-label"></label>
                <input asp-for="DiemThang10" class="form-control" />
                <span asp-validation-for="DiemThang10" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiemThang4" class="control-label"></label>
                <input asp-for="DiemThang4" class="form-control" />
                <span asp-validation-for="DiemThang4" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="DiemRenLuyen" class="control-label"></label>
                <input asp-for="DiemRenLuyen" class="form-control" />
                <span asp-validation-for="DiemRenLuyen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="XepLoai" class="control-label"></label>
                <input asp-for="XepLoai" class="form-control" />
                <span asp-validation-for="XepLoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoTinChi" class="control-label"></label>
                <input asp-for="SoTinChi" class="form-control" />
                <span asp-validation-for="SoTinChi" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group mt-2">
        @*<input type="submit" value="Thêm" class="btn btn-primary" />*@
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-plus"></i> Thêm</button>
    </div>
</form>
    <div class="mt-4">
        <a class="btn btn-outline-primary" asp-action="Index"><i class="fas fa-long-arrow-alt-left"></i> Quay lại trang trước</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

ProjectA.DKHBSolution/ProjectA/Views/SinhVien/CreateNewSinhVien.cshtml
@model ProjectA.Models.SinhVien

@{
    ViewData["Title"] = "CreateNewSinhVien";
}

<h2>Thêm sinh viên mới</h2>

<hr />
<form asp-action="CreateNewSinhVien">
    <div class="row">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdSinhVien" class="control-label"></label>
                <input asp-for="IdSinhVien" class="form-control" />
                <span asp-validation-for="IdSinhVien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenSinhVien" class="control-label"></label>
                <input asp-for="TenSinhVien" class="form-control" />
                <span asp-validation-for="TenSinhVien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdLop" class="control-label"></label>
                <select asp-for="IdLop" class="form-control"
                        asp-items="@(new SelectList(ViewBag.Lops,"IdLop","IdLop"))">
                </select>
                <span asp-validation-for="IdLop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label"></label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordSv" class="control-label"></label>
                <input asp-for="PasswordSv" class="form-control" />
                <span asp-validation-for="PasswordSv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>

        </div>
    </div>
    <div class="form-group mt-2">
        @*<input type="submit" value="Thêm" class="btn btn-primary" />*@
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-plus"></i> Thêm</button>
    </div>
</form>
<div class="mt-5">
    <a class="btn btn-outline-primary" asp-action="Index"><i class="fas fa-long-arrow-alt-left"></i> Quay lại trang trước</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectA.DKHBSolution/ProjectA/Views/SinhVien/Delete.cshtml
@model ProjectA.Models.SinhVien

@{
    ViewData["Title"] = "Confirmation";
}

<p class="p-3 alert-danger">Are you sure you want to delete this?</p>

<div>
    <p class="h3">@Model.TenSinhVien</p>
    <hr />
    <dl class="row">
        <dt class="col-sm-2"><label asp-for="IdSinhVien"></label></dt>
        <dd class="col-sm-10">@Model.IdSinhVien</dd>
        <dt class="col-sm-2"><label asp-for="TenSinhVien"></label></dt>
        <dd class="col-sm-10">@Model.TenSinhVien</dd>
        <dt class="col-sm-2"><label asp-for="IdLop"></label></dt>
        <dd class="col-sm-10">@Model.IdLop</dd>
        <dt class="col-sm-2"><label asp-for="NgaySinh"></label></dt>
        <dd class="col-sm-10">@Model.NgaySinh</dd>
        <dt class="col-sm-2"><label asp-for="Email"></label></dt>
        <dd class="col-sm-10">@Model.Email</dd>
        <dt class="col-sm-2"><label asp-for="PasswordSv"></label></dt>
        <dd class="col-sm-10">@Model.PasswordSv</dd>
        <dt class="col-sm-2"><label asp-for="SoDienThoai"></label></dt>
        <dd class="col-sm-10">@Model.SoDienThoai</dd>
        <dt class="col-sm-2"><label asp-for="GioiTinh"></label></dt>
        <dd class="col-sm-10">@Model.GioiTinh</dd>
        <dt class="col-sm-2"><label asp-for="DiaChi"></label></dt>
        <dd class="col-sm-10">@Model.DiaChi</dd>
    </dl>
</div>

<hr />

<form asp-action="Delete">
    <input type="hidden" asp-for="IdSinhVien" />
    <input type="submit" value="Delete" class="btn btn-outline-danger btn-sm" 
           onclick="return confirm('Bạn chắc chắn muốn xóa sinh viên này?')"/> |
    
    <a asp-action="Index" class="btn btn-sm btn-outline-secondary">Back to List</a>
</form>

ProjectA.DKHBSolution/ProjectA/Views/SinhVien/Details.cshtml
@model ProjectA.ViewModel.XetHocBongViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Chi Tiết</h1>
<h4 class="my-4">Sinh Viên</h4>
<hr />
<div>
    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.TenSinhVien)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.TenSinhVien)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.IdLop)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.IdLop)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.PasswordSv)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.PasswordSv)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.NgaySinh)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.NgaySinh)
                </dd>
            </dl>
        </div>
        <div class="col-md-6">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.SoDienThoai)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.SoDienThoai)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.GioiTinh)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.GioiTinh)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.DiaChi)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.DiaChi)
                </dd>
            </dl>
        </div>
    </div>
    @*<dl class="row">
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.TenSinhVien)
            </dt>
            <dd class="col-sm-12">
                @Html.DisplayFor(model => model.TenSinhVien)
            </dd>
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.IdLop)
            </dt>
            <dd class="col-sm-12">
                @Html.DisplayFor(model => model.IdLop)
            </dd>
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.PasswordSv)
            </dt>
            <dd class="col-sm-12">
                @Html.DisplayFor(model => model.PasswordSv)
            </dd>
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.NgaySinh)
            </dt>
            <dd class="col-sm-12">
                @Html.DisplayFor(model => model.NgaySinh)
            </dd>
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-12">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </dt>
            <dd class="col-sm-12">
                @Html.DisplayFor(model => model.SoDienThoai)
            </dd>
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.GioiTinh)
            </dt>
            <dd class="col-sm-12">
                @Html.DisplayFor(model => model.GioiTinh)
            </dd>
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>
            <dd class="col-sm-12">
                @Html.DisplayFor(model => model.DiaChi)
            </dd>

        </dl>*@
</div>
<div class="mt-5">
    <a class="btn btn-outline-primary" asp-action="Index"><i class="fas fa-long-arrow-alt-left"></i> Quay lại trang trước</a>
</div>

ProjectA.DKHBSolution/ProjectA/Views/SinhVien/Edit.cshtml
@model ProjectA.Models.SinhVien

@{
    ViewData["Title"] = "Edit";
}

<h2>Cập nhật</h2>

<h4 class="my-4">Sinh Viên</h4>
<hr />
<form asp-action="Edit">
    <div class="row">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdSinhVien" />
            <div class="form-group">
                <label asp-for="TenSinhVien" class="control-label"></label>
                <input asp-for="TenSinhVien" class="form-control" />
                <span asp-validation-for="TenSinhVien" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdLop" class="control-label"></label>
                <select asp-for="IdLop" class="form-control"
                        asp-items="@(new SelectList(ViewBag.Lops,"IdLop","IdLop"))">
                </select>
                <span asp-validation-for="IdLop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordSv" class="control-label"></label>
                <input asp-for="PasswordSv" class="form-control" />
                <span asp-validation-for="PasswordSv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label"></label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group mt-3">
        @*<input type="submit" value="Cập Nhật" class="btn btn-primary" />*@
        <button class="btn btn-outline-success" type="submit"><i class="far fa-edit"></i> Cập Nhật</button>
        
    </div>
</form>
<div>
    <a class="btn btn-outline-primary" asp-action="Index"><i class="fas fa-long-arrow-alt-left"></i> Quay lại trang trước</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectA.DKHBSolution/ProjectA/Views/SinhVien/Index.cshtml
@model IEnumerable<ProjectA.ViewModel.XetHocBongViewModel>
@{Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Active"] = "SV";}

@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <div class="container">
        <form method="post" asp-controller="SinhVien" asp-action="Index" enctype="multipart/form-data"> 
            <input type="file" name="file"/>
            <button type="submit">Import form excel</button>
        </form>
    </div>
</div>*@
<h2>Bảng điểm</h2>
<a asp-controller="SinhVien" class="btn btn-outline-primary my-3" asp-action="Create"><i class="fas fa-plus"></i> Tạo bảng điểm mới</a>
<div class="table-responsive">
    <table class="table align-middle table-bordered">
        <thead class="table-dark table align-middle">
            <tr class="align-middle">
                <th class="align-middle">@Html.DisplayNameFor(model => model.IdSinhVien)</th>
                <th class="align-middle">@Html.DisplayNameFor(model => model.TenSinhVien)</th>
                <th class="align-middle">@Html.DisplayNameFor(model => model.IdHocKy)</th>
                <th class="align-middle">@Html.DisplayNameFor(model => model.IdLop)</th>
                <th class="align-middle">@Html.DisplayNameFor(model => model.DiemThang4)</th>
                <th class="align-middle">@Html.DisplayNameFor(model => model.DiemThang10)</th>
                <th class="align-middle">@Html.DisplayNameFor(model => model.DiemRenLuyen)</th>
                <th class="align-middle">@Html.DisplayNameFor(model => model.XepLoai)</th>
            </tr>
        </thead>
        <tbody class="align-middle">
            @foreach (var item in Model)
            {
            <tr class="align-middle">
                <td class="align-middle">@item.IdSinhVien</td>
                <td class="align-middle">@item.TenSinhVien</td>
                <td class="align-middle">@item.IdHocKy</td>
                <td class="align-middle">@item.IdLop</td>
                <td class="align-middle">@item.DiemThang4</td>
                <td class="align-middle">@item.DiemThang10</td>
                <td class="align-middle">@item.DiemRenLuyen</td>
                <td class="align-middle">@item.XepLoai</td>
                <td class="align-middle">
                    <a asp-action="Edit" asp-route-id="@item.IdSinhVien" class="my-1 btn btn-sm btn-outline-info"><i class="far fa-edit"></i> Cập nhập</a>
                    <a asp-action="Details"  class="btn btn-sm btn-outline-dark my-1" asp-route-id="@item.IdSinhVien"><i class="far fa-file-alt"></i> Chi tiết</a>
                    <a asp-action="Delete" class="btn btn-sm btn-outline-danger my-1" asp-route-id="@item.IdSinhVien"><i class="far fa-trash-alt"></i> Xoá</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
    @*<ul class="pagination">*@
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @{
                int numberPage = ViewBag.numberPage;
                int pageCurrent = ViewBag.pageCurrent;
                int offset = 2;//number display page

                //config FirstLink
                if (pageCurrent > 1)
                {
                    int prevPage = pageCurrent - 1;
                    var PrevLink = new Dictionary<string, string> { { "page", prevPage.ToString() } };
                    <li class="page-item">
                        <a class="page-link" aria-label="Previous" asp-controller="SinhVien" asp-action="Index" asp-all-route-data="PrevLink">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    @*<li><a asp-controller="SinhVien" asp-action="Index" asp-all-route-data="PrevLink">Prev Link</a></li>*@
                }

                int from = pageCurrent - offset;
                int to = pageCurrent + offset;
                if (from <= 0)
                {
                    from = 1;
                    to = offset * 2;
                }


                if (to > numberPage)
                {
                    to = numberPage;
                }

                int i;
                for (i = from; i <= to; i++)
                {
                    var parms = new Dictionary<string, string>
                                        {
                { "page",i.ToString()}
            };
                    if (pageCurrent == i)
                    {
                        <li class="page-item active"><a class="page-link" asp-controller="SinhVien" asp-action="Index" asp-all-route-data="parms">@i</a></li>
                        @*<li class="active"><a asp-controller="SinhVien" asp-action="Index" asp-all-route-data="parms">@i</a></li>*@
                    }
                    else
                    {
                        <li class="page-item"><a class="page-link" asp-controller="SinhVien" asp-action="Index" asp-all-route-data="parms">@i</a></li>
                        @*<li><a asp-controller="SinhVien" asp-action="Index" asp-all-route-data="parms">@i</a></li>*@
                    }

                }

                if (pageCurrent < numberPage)
                {
                    int nextPage = pageCurrent + 1;
                    var NextLink = new Dictionary<string, string> { { "page", nextPage.ToString() } };
                    <li class="page-item">
                        <a class="page-link" asp-controller="SinhVien" asp-action="Index" asp-all-route-data="NextLink" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    @*<li><a asp-controller="SinhVien" asp-action="Index" asp-all-route-data="NextLink">Next Link</a></li>*@
                }

                if (pageCurrent < numberPage - (to / 2))
                {
                    var LastLink = new Dictionary<string, string> { { "page", numberPage.ToString() } };
                    <li class="page-item">
                        <a class="page-link" asp-controller="SinhVien" asp-action="Index" asp-all-route-data="LastLink">
                            <span aria-hidden="true">&#8921;</span>
                        </a>
                    </li>
                    @*<li><a asp-controller="SinhVien" asp-action="Index" asp-all-route-data="LastLink">Last Link</a></li>*@
                }
            }

        </ul>
    </nav>
    @*</ul>*@